In [25]:
import pandas as pd
import json

df = pd.read_json('model-training/data/reviews_carsurvej.json')

df_parsed = df[0].apply(json.loads).apply(pd.Series)
df_parsed

,Model name:,Summary:,Faults:,General Comments:,Model year,Year of manufacture,First year of ownership,Most recent year of ownership,Engine and transmission,Performance marks,Reliability marks,Comfort marks,Dealer Service marks,Running Costs (higher is cheaper),Overall marks (average of all marks),Distance when acquired,Most recent distance,Previous car
0,2017 BMW 1 Series M140i 3.0 turbo petrol from ...,Performance bargain with real character,Brake squeal in reverse (cured itself after ab...,It's exceeded every expectation.The B58 turbo ...,2017,2017,2017,2018,3.0 turbo petrol Automatic,10 / 10,9 / 10,7 / 10,10 / 10,6 / 10,8.4 / 10,8 miles,29000 miles,Volkswagen CC
1,2015 BMW 1 Series 118i Sport 1.6 from UK and I...,Great car to drive,"So far nothing, isn't it fantastic.","Great car to drive, good performance and handl...",2015,2015,2015,NaN,1.6 Automatic,8 / 10,9 / 10,6 / 10,8 / 10,8 / 10,7.8 / 10,5 miles,32000 miles,Toyota Corolla
2,2014 BMW 1 Series 116d M Sport turbo diesel fr...,Good little car,One time the clutch juddered while pulling awa...,I hired this car for two weeks while I was vis...,2014,2014,2014,2014,turbo diesel Manual,7 / 10,NaN,8 / 10,NaN,7 / 10,7.3 / 10,2000 miles,3200 miles,Ford Focus
3,2012 BMW 1 Series 118i Sport 1.6 TwinTurbo fro...,"New = Lemon, Old = Gem",1. Air-conditioning malfunction at 3000 km (I ...,"I'm a young working individual, hoping to trus...",2012,2012,2012,2012,1.6 TwinTurbo Semi-Automatic,6 / 10,0 / 10,5 / 10,10 / 10,9 / 10,6.0 / 10,0 kilometres,9510 kilometres,Opel Astra
4,2011 BMW 1 Series 120d M Sport 2.0 turbo diese...,Nice little car which is fast and economical,Nothing apart from wear and tear items.,I bought this car as a cheaper to run replacem...,2011,2011,2019,2019,2.0 turbo diesel Manual,8 / 10,10 / 10,8 / 10,NaN,9 / 10,8.8 / 10,69000 miles,74999 miles,BMW 3 Series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77027,2003 Volvo XC90 T6 2.9 liter from North America,LAST time would own or want to drive one,Tranny slipping at 83000 miles; it will cost $...,Slow pick-up.E-mail me: bobmarley_93@hotmail.c...,NaN,2003,2007,2008,2.9 liter Automatic,1 / 10,0 / 10,5 / 10,0 / 10,0 / 10,1.2 / 10,74000 miles,83000 miles,Nissan Pathfinder
77028,2003 Volvo XC90 T6 AWD 6 Cylider Twin turbo fr...,Ride and performance are inferior to the compe...,Audio system failure. Needed to be resolved wi...,The XC 90 is quiet and comfortable on the high...,NaN,2003,2003,2004,6 Cylider Twin turbo Don't Know,7 / 10,7 / 10,6 / 10,6 / 10,5 / 10,6.2 / 10,15 miles,29000 miles,Chevrolet Venture
77029,2003 Volvo XC90 T6 AWD 6 Cylider Twin turbo fr...,Ride and performance are inferior to the compe...,Audio system failure. Needed to be resolved wi...,The XC 90 is quiet and comfortable on the high...,NaN,2003,2003,2004,6 Cylider Twin turbo Don't Know,7 / 10,7 / 10,6 / 10,6 / 10,5 / 10,6.2 / 10,15 miles,29000 miles,Chevrolet Venture
77030,2003 Volvo XC90 T6 AWD 6 Cylider Twin turbo fr...,Ride and performance are inferior to the compe...,Audio system failure. Needed to be resolved wi...,The XC 90 is quiet and comfortable on the high...,NaN,2003,2003,2004,6 Cylider Twin turbo Don't Know,7 / 10,7 / 10,6 / 10,6 / 10,5 / 10,6.2 / 10,15 miles,29000 miles,Chevrolet Venture
77031,2002 Volvo XC90 T6 Twin turbo from North America,The interior of this car seems like a toy,The steering wheel was off center had to be al...,This car has great trunk space.I love the seve...,NaN,2002,2002,2004,Twin turbo Automatic,NaN,NaN,NaN,NaN,NaN,NaN,20 miles,12000 miles,BMW 5 Series

In [26]:
df_parsed.isna().any()

Model name:                             False
Summary:                                 True
Faults:                                  True
General Comments:                        True
Model year                               True
Year of manufacture                     False
First year of ownership                  True
Most recent year of ownership            True
Engine and transmission                 False
Performance marks                        True
Reliability marks                        True
Comfort marks                            True
Dealer Service marks                     True
Running Costs (higher is cheaper)        True
Overall marks (average of all marks)     True
Distance when acquired                   True
Most recent distance                     True
Previous car                             True
dtype: bool

In [27]:
df_parsed[df_parsed['Summary:'].isna()]

,Model name:,Summary:,Faults:,General Comments:,Model year,Year of manufacture,First year of ownership,Most recent year of ownership,Engine and transmission,Performance marks,Reliability marks,Comfort marks,Dealer Service marks,Running Costs (higher is cheaper),Overall marks (average of all marks),Distance when acquired,Most recent distance,Previous car
84,2006 BMW 3 Series 325i 2.5 litre inline 6 cyli...,NaN,"I purchased a car from a dealer in Folsom, Cal...","Ride quality was good, handling was exceptiona...",2006,2006,2012,NaN,2.5 litre inline 6 cylinder Automatic,NaN,7 / 10,6 / 10,6 / 10,6 / 10,6.3 / 10,68000 miles,189600 miles,NaN
85,2006 BMW 3 Series 325i 2.5 litre inline 6 cyli...,NaN,"I purchased a car from a dealer in Folsom, Cal...","Ride quality was good, handling was exceptiona...",2006,2006,2012,NaN,2.5 litre inline 6 cylinder Automatic,NaN,7 / 10,6 / 10,6 / 10,6 / 10,6.3 / 10,68000 miles,189600 miles,NaN
86,2006 BMW 3 Series 325i 2.5 litre inline 6 cyli...,NaN,"I purchased a car from a dealer in Folsom, Cal...","Ride quality was good, handling was exceptiona...",2006,2006,2012,NaN,2.5 litre inline 6 cylinder Automatic,NaN,7 / 10,6 / 10,6 / 10,6 / 10,6.3 / 10,68000 miles,189600 miles,NaN
113,2004 BMW 3 Series 330xi AWD 3.0 from North Ame...,NaN,"- Ball joint developed play, and replaced the ...",I bought this car for its AWD as I live on a h...,2004,2004,2014,2015,3.0 Automatic,8 / 10,6 / 10,9 / 10,NaN,5 / 10,7.0 / 10,128000 miles,151000 miles,BMW 3 Series
114,2004 BMW 3 Series 330xi AWD 3.0 from North Ame...,NaN,"- Ball joint developed play, and replaced the ...",I bought this car for its AWD as I live on a h...,2004,2004,2014,2015,3.0 Automatic,8 / 10,6 / 10,9 / 10,NaN,5 / 10,7.0 / 10,128000 miles,151000 miles,BMW 3 Series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76980,2004 Volvo XC90 T6 2.9T from North America,NaN,Car seemed almost new as I test drove it a few...,"Despite reading threads, bulletin boards and b...",2004,2004,2009,2009,2.9T Semi-Automatic,6 / 10,6 / 10,8 / 10,NaN,5 / 10,6.3 / 10,64000 miles,68000 miles,Volvo XC90
76981,2004 Volvo XC90 T6 2.9T from North America,NaN,Car seemed almost new as I test drove it a few...,"Despite reading threads, bulletin boards and b...",2004,2004,2009,2009,2.9T Semi-Automatic,6 / 10,6 / 10,8 / 10,NaN,5 / 10,6.3 / 10,64000 miles,68000 miles,Volvo XC90
76982,2004 Volvo XC90 T6 2.9T from North America,NaN,Car seemed almost new as I test drove it a few...,"Despite reading threads, bulletin boards and b...",2004,2004,2009,2009,2.9T Semi-Automatic,6 / 10,6 / 10,8 / 10,NaN,5 / 10,6.3 / 10,64000 miles,68000 miles,Volvo XC90
76999,2004 Volvo XC90 from North America,NaN,"Transmission went at 62,000 miles. Drove it in...","Definitely love the ride, comfort, and perform...",2004,2004,2004,2007,Automatic,8 / 10,3 / 10,8 / 10,1 / 10,5 / 10,5.0 / 10,0 miles,62000 miles,Ford Explorer
77000,2004 Volvo XC90 from North America,NaN,"Transmission went at 62,000 miles. Drove it in...","Definitely love the ride, comfort, and perform...",2004,2004,2004,2007,Automatic,8 / 10,3 / 10,8 / 10,1 / 10,5 / 10,5.0 / 10,0 miles,62000 miles,Ford Explorer

In [28]:
df_parsed_filled = df_parsed[~df_parsed['General Comments:'].isna()]

In [29]:
df_parsed_filled['Faults:'].fillna('Without faults', inplace=True)
df_parsed_filled['Summary:'].fillna('Stock car', inplace=True)

/var/folders/kq/k4c0ss5j4ync13791_11l7qr0000gn/T/ipykernel_56504/1569569874.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_parsed_filled['Faults:'].fillna('Without faults', inplace=True)
/var/folders/kq/k4c0ss5j4ync13791_11l7qr0000gn/T/ipykernel_56504/1569569874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_parsed_filled['Faults:'].fillna('Without faults', inplace=True)
/var/folders/kq/k4c0ss5j4ync13791_11l7qr0000gn/T/ipykernel_56504/1569569874.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_parsed_filled['Summary:'].fillna('Stock car', inplace=True)
/var/folders/kq/k4c0ss5j4ync13791_11l7qr0000gn/T/ipykernel_56504/1569569874.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_parsed_filled['Summary:'].fillna('Stock car', inplace=True)

In [30]:
df_parsed_filled.isna().any()

Model name:                             False
Summary:                                False
Faults:                                 False
General Comments:                       False
Model year                               True
Year of manufacture                     False
First year of ownership                  True
Most recent year of ownership            True
Engine and transmission                 False
Performance marks                        True
Reliability marks                        True
Comfort marks                            True
Dealer Service marks                     True
Running Costs (higher is cheaper)        True
Overall marks (average of all marks)     True
Distance when acquired                   True
Most recent distance                     True
Previous car                             True
dtype: bool

,Model name:,Summary:,Faults:,General Comments:,Model year,Year of manufacture,First year of ownership,Most recent year of ownership,Engine and transmission,Performance marks,Reliability marks,Comfort marks,Dealer Service marks,Running Costs (higher is cheaper),Overall marks (average of all marks),Distance when acquired,Most recent distance,Previous car
182,2002 BMW 3 Series 320iA 2.2 liter six cylinder...,Comfortable tourer for two people,NaN,One word: sound. The cabin is filled with an i...,NaN,2002,2003,2003,2.2 liter six cylinder Automatic,8 / 10,10 / 10,9 / 10,NaN,4 / 10,7.8 / 10,11000 kilometres,13000 kilometres,BMW 3 Series
183,2002 BMW 3 Series 320iA 2.2 liter six cylinder...,Comfortable tourer for two people,NaN,One word: sound. The cabin is filled with an i...,NaN,2002,2003,2003,2.2 liter six cylinder Automatic,8 / 10,10 / 10,9 / 10,NaN,4 / 10,7.8 / 10,11000 kilometres,13000 kilometres,BMW 3 Series
935,2000 BMW 5 Series 520i 2.2 from UK and Ireland,"Above the rest, perfect",NaN,"I used to own BMW 328I SE, 1998, but this car ...",2000,2000,2005,2005,2.2 Semi-Automatic,8 / 10,9 / 10,9 / 10,8 / 10,6 / 10,8.0 / 10,29000 miles,34000 miles,BMW 3 Series
936,2000 BMW 5 Series 520i 2.2 from UK and Ireland,"Above the rest, perfect",NaN,"I used to own BMW 328I SE, 1998, but this car ...",2000,2000,2005,2005,2.2 Semi-Automatic,8 / 10,9 / 10,9 / 10,8 / 10,6 / 10,8.0 / 10,29000 miles,34000 miles,BMW 3 Series
937,2000 BMW 5 Series 520i 2.2 from UK and Ireland,"Above the rest, perfect",NaN,"I used to own BMW 328I SE, 1998, but this car ...",2000,2000,2005,2005,2.2 Semi-Automatic,8 / 10,9 / 10,9 / 10,8 / 10,6 / 10,8.0 / 10,29000 miles,34000 miles,BMW 3 Series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76385,2001 Volvo S60 Base 2.4 from North America,Great car!!!,NaN,"Great car, I bought the car used, but you can ...",NaN,2001,2002,2002,2.4 Automatic,10 / 10,10 / 10,8 / 10,10 / 10,5 / 10,8.6 / 10,13000 miles,16000 miles,Honda Accord
76560,1999 Volvo S80 2.9 from North America,Trash,NaN,"Head gasket blew at 75,000 miles.Heating core ...",NaN,1999,2005,2010,2.9 Automatic,2 / 10,1 / 10,8 / 10,2 / 10,10 / 10,4.6 / 10,130000 miles,NaN,Mazda Millenia
76561,1999 Volvo S80 2.9 from North America,Trash,NaN,"Head gasket blew at 75,000 miles.Heating core ...",NaN,1999,2005,2010,2.9 Automatic,2 / 10,1 / 10,8 / 10,2 / 10,10 / 10,4.6 / 10,130000 miles,NaN,Mazda Millenia
76562,1999 Volvo S80 2.9 from North America,Trash,NaN,"Head gasket blew at 75,000 miles.Heating core ...",NaN,1999,2005,2010,2.9 Automatic,2 / 10,1 / 10,8 / 10,2 / 10,10 / 10,4.6 / 10,130000 miles,NaN,Mazda Millenia
76563,1999 Volvo S80 2.9 from North America,Trash,NaN,"Head gasket blew at 75,000 miles.Heating core ...",NaN,1999,2005,2010,2.9 Automatic,2 / 10,1 / 10,8 / 10,2 / 10,10 / 10,4.6 / 10,130000 miles,NaN,Mazda Millenia

In [ ]:
df_restored = df_parsed.apply(lambda x: json.dumps(x.to_dict()), axis=1).to_frame()
df_restored.to_json('restored_reviews.json', orient='records', lines=True)  # or without 'lines=True' for array format

In [32]:
with open('restored_reviews_carsurvej.json', 'w', encoding='utf-8') as f:
    json.dump(df_parsed.to_dict(orient='records'), f, indent=2, ensure_ascii=False)